### PR TITLE
Change default reader url schema to https

### LINKED ISSUE #132: Change links for uploaded files to https.
Make sure these boxes are checked before submitting your issue -- thank you!

- [ √ ] Check that you are using the [latest version](https://github.com/unfoldingWord-dev/ts-desktop/releases/latest) of the app.
- [ √ ] Check that a similar issue has not already been opened.

As a technical worker, I would like the URL provided by BTT-Writer after an upload to be to a secure link (https) rather than insecure.

### PR DESCRIPTION
**Pull request by mXaln**
Fixes #132.

Changes in this pull request:
- Set default reader url schema to https

### CODE REVIEW

**Comment by mXaln** [comment]
For the change to take effect, one needs to reset BTT-Writer application data. Or manually change to https in settings.

**Comment by PurpleGuitar** [comment]
Max, thanks for making this change.  I realize in reviewing it that it's still pointing to the old live reader.  Please change the WACS reader location from:

https://read.bibletranslationtools.org/u

to:

https://read.bibleineverylanguage.org

Let's do this for both Android and Desktop.

**Comment by mXaln** [comment]
> Max, thanks for making this change. I realize in reviewing it that it's still pointing to the old live reader. Please change the WACS reader location from:
> 
> https://read.bibletranslationtools.org/u
> 
> to:
> 
> https://read.bibleineverylanguage.org
> 
> Let's do this for both Android and Desktop.

@PurpleGuitar Done.

**Comment by PurpleGuitar** [comment]
Tested on desktop and it works.  Looks good!

**Review by PurpleGuitar — APPROVED** [review]

**Pull request merged**
